/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from "react";
import {
  Platform,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from "react-native";
import Espressif from "react-native-espressif";

export default class App extends Component<{}> {
  constructor(props) {
    super(props);

    this.state = {
      status: "Initializing",
      devices: []
    };

    this.espressif = new Espressif();

    this.scanDevices = this.scanDevices.bind(this);
  }

  async componentDidMount() {
    console.info(Espressif);

    try {
      await this.espressif.setConfig({
        [Espressif.Options.TRANSPORT]: Espressif.ConnectionType.Bluetooth,
        [Espressif.Options.SECURITY]: Espressif.Security.Sec1
      });

      console.info(this.espressif);

      this.espressif.onStateChanged((state, devices) =>
        this.setState({ devices })
      );

      this.setState({ status: "Ready" });
      console.info("Espressif configured");
    } catch (e) {
      console.error(e);
      this.setState({ status: "Error" });
    }

    // Espressif.scanDevices();
  }

  scanDevices() {
    this.espressif.scanDevices();
  }

  render() {
    const { status, devices = [] } = this.state;

    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Espressif example</Text>
        <Text style={styles.instructions}>STATUS: {status}</Text>

        <TouchableOpacity onPress={this.scanDevices}>
          <Text style={styles.scanDevices}>Scan devices</Text>
        </TouchableOpacity>

        <View style={styles.list}>
          {(devices || []).map(device => (
            <TouchableOpacity
              key={device.uuid}
              onPress={() => {
                this.espressif.connectTo(device.uuid);
              }}
              style={{
                shadowColor: "black",
                shadowOffset: { width: 0, height: 2 },
                shadowRadius: 2,
                shadowOpacity: 0.15
              }}
            >
              <View style={styles.item}>
                <Text
                  style={{
                    color: "#333333"
                  }}
                >
                  {device.name}
                </Text>
                <Text
                  style={{
                    color: "#666666",
                    fontSize: 12
                  }}
                >
                  {device.uuid}
                </Text>
                <Text
                  style={{
                    color: "#666666",
                    fontSize: 12
                  }}
                >
                  {device.state}
                </Text>
              </View>
            </TouchableOpacity>
          ))}
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  welcome: {
    fontSize: 20,
    textAlign: "center",
    margin: 10
  },
  instructions: {
    textAlign: "center",
    color: "#333333",
    marginBottom: 5
  },
  scanDevices: {
    backgroundColor: "#00A86B",
    fontSize: 18,
    fontWeight: "100",
    padding: 20,
    borderRadius: 8,
    overflow: "hidden"
  },
  list: {
    flex: 1,
    marginTop: 20
  },
  item: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 8,
    overflow: "hidden"
  }
});
