/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from "react";
import { SafeAreaView, Image, View } from "react-native";
import { createAppContainer } from "react-navigation";
import { createDrawerNavigator, DrawerActions } from "react-navigation-drawer";
import { TouchableOpacity } from "react-native-gesture-handler";

import Home from "./containers/Home";
import Settings from "./containers/Settings";

const AppNavigator = createDrawerNavigator({
  Home,
  Settings
});

const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  constructor(props) {
    super(props);

    this.container = React.createRef();

    this.toggleDrawer = this.toggleDrawer.bind(this);
  }

  toggleDrawer() {
    this.container.current.dispatch(DrawerActions.toggleDrawer());
  }

  render() {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: "#F5FCFF" }}>
        <View
          style={{
            position: "absolute",
            top: 25,
            left: 10,
            zIndex: 1
          }}
        >
          <TouchableOpacity onPress={this.toggleDrawer}>
            <Image
              resizeMode="contain"
              style={{ width: 30 }}
              source={require("./assets/menu.png")}
            />
          </TouchableOpacity>
        </View>
        <AppContainer ref={this.container} style={{ flex: 1 }} />
      </SafeAreaView>
    );
  }
}
