platform :ios, '10.0'

	target 'EspressifSample' do
#		use_frameworks!
    # use_modular_headers!
		rn_path = '../node_modules/react-native'

		pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
		pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
    pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/GLog.podspec", :modular_headers => false

    pod 'React', :path => "#{rn_path}/"
    pod 'React-Core', :path => "#{rn_path}/React"
    pod 'React-DevSupport', :path => "#{rn_path}/React"
    pod 'React-RCTActionSheet', :path => "#{rn_path}/Libraries/ActionSheetIOS"
    pod 'React-RCTAnimation', :path => "#{rn_path}/Libraries/NativeAnimation"
    pod 'React-RCTBlob', :path => "#{rn_path}/Libraries/Blob"
    pod 'React-RCTImage', :path => "#{rn_path}/Libraries/Image"
    pod 'React-RCTLinking', :path => "#{rn_path}/Libraries/LinkingIOS"
    pod 'React-RCTNetwork', :path => "#{rn_path}/Libraries/Network"
    pod 'React-RCTSettings', :path => "#{rn_path}/Libraries/Settings"
    pod 'React-RCTText', :path => "#{rn_path}/Libraries/Text"
    pod 'React-RCTVibration', :path => "#{rn_path}/Libraries/Vibration"
    pod 'React-RCTWebSocket', :path => "#{rn_path}/Libraries/WebSocket"
    pod 'React-cxxreact', :path => "#{rn_path}/ReactCommon/cxxreact"
    pod 'React-jsi', :path => "#{rn_path}/ReactCommon/jsi"
    pod 'React-jsiexecutor', :path => "#{rn_path}/ReactCommon/jsiexecutor"
    pod 'React-jsinspector', :path => "#{rn_path}/ReactCommon/jsinspector"

		# pod 'React', path: rn_path, subspecs: [
		# 	'Core',
		# 	'CxxBridge',
		# 	'RCTAnimation',
		# 	'RCTActionSheet',
		# 	'RCTImage',
		# 	'RCTLinkingIOS',
		# 	'RCTNetwork',
		# 	'RCTSettings',
		# 	'RCTText',
		# 	'RCTVibration',
		# 	'RCTWebSocket',
		# 	'RCTPushNotification',
		# 	'RCTCameraRoll',
		# 	'RCTSettings',
		# 	'RCTBlob',
		# 	'RCTGeolocation',
		# 	'DevSupport'
		# ]

		pod 'react-native-espressif', :path => '../../react-native-espressif.podspec'
   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

   pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

   pod 'RNScreens', :path => '../node_modules/react-native-screens'

	end
